# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2025-12
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2025-12@sha256:03cdafe4cafaeea9ee23b306f484633f5381f7058b4f80f4e6c5efbfd32cb466"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
