# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2025-09
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2025-09@sha256:622cf05b8b972e8e54fc89edc0ffb3b5106ba871e9a7a2716b4f50369a7ae648"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
